dyasynora_app/urls.py
from django.urls import path
from . import views
from .views import PostListView, ProjectDetailView, PostCreateView, ProjectUpdateView, ProjectDeleteView, UserDetailView, SearchResultsView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='dyasynora_app-diasynora'),
    path('crowdsourcers/', views.crowdsourcers, name='dyasynora_app-crowdsourcers'),
    path('projects/', PostListView.as_view(), name='dyasynora_app-feed'),
    path('my-projects', views.user_projects, name='user-projects'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='dyasynora_app-project-detail'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='dyasynora_app-profile-detail'),
    path('project/new/', PostCreateView.as_view(), name='dyasynora_app-project-create'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='update-project'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete-project'),
    path('our-mission/', views.our_mission, name='dyasynora_app-our-mission'),
    path('leaders/', views.leaders, name='dyasynora_app-leaders'),
    path('payment/', views.payment, name='dyasynora_app-payment'),
    path('new_activity/', views.new_activity, name='new activity'),
    path('add/project/', views.add_project, name='project-create'),
    path('add/event/', views.add_event, name='event-create'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dyasynora_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.views import ProfileDetailView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('dyasynora_app.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dyasynora_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from PIL import Image
from django.http import JsonResponse
from location_field.models.plain import PlainLocationField
from ckeditor_uploader.fields import RichTextUploadingField

from django.urls import reverse
from django.conf import settings
# Each class is table in database
class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(default='default_proj.jpg', upload_to='project_pics')
    story = RichTextUploadingField(blank=True, null=True, config_name='special')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # if a user is deleted, also delete their projects
    date_created = models.DateTimeField(default=timezone.now) # actual timezone function is passed
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    supporters = models.IntegerField(default=0)
    city = models.CharField(max_length=255, blank=True, null=True)
    org = models.CharField(max_length=255, blank=True, null=True)
    org_desc =  models.TextField(blank=True, null=True)
    location = models.CharField(blank=True, max_length=255, null=True)
    stage = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=29, blank=True, null=True)
    description = models.TextField(blank=True, null=True) # Unrestricted version of CharField

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('dyasynora_app-project-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super(Project, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Event(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE) # if a project is deleted, also delete its volunteering event
    name = models.CharField(max_length=50)
    organiser = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # if a user is deleted, also delete their volunteering instance/link
    start_datetime = models.DateTimeField('%d/%m/%Y %H:%M:%S', blank=True, null=True)
    end_datetime = models.DateTimeField('%d/%m/%Y %H:%M:%S', blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    image = models.ImageField(default='default_proj.jpg', upload_to='event_pics')

    def save(self, *args, **kwargs):
        super(Event, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def add_event(self, event):
        if self.event_set.count() >= 5:
            raise Exception("Too many events on this project")

        self.event_set.add(event)

class Campaign(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True) # if a project is deleted, also delete the campaign
    title = models.CharField(max_length=50)
    organiser = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    campaign_start = models.DateTimeField('%d/%m/%Y', default=timezone.now)
    campaign_end = models.DateTimeField('%d/%m/%Y', default=timezone.now)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField(blank=True, null=True) # Unrestricted version of CharField
    image = models.ImageField(default='default_proj.jpg', upload_to='campaign_pics')

    def save(self, *args, **kwargs):
        super(Campaign, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Opportunity(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True) # if a project is deleted, also delete the opportunity
    title = models.CharField(max_length=50)
    opportunity_datetime = models.DateTimeField('%d/%m/%Y %H:%M:%S', default=timezone.now)
    description = models.TextField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    image = models.ImageField(default='default_proj.jpg', upload_to='opportunity_pics')

    def save(self, *args, **kwargs):
        super(Opportunity, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class BlogPost(models.Model):
    title = models.CharField(max_length=50)
    content = RichTextUploadingField(blank=True, null=True, config_name='special')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_posted = models.DateTimeField(default=timezone.now) # actual timezone function is passed
    category = models.CharField(max_length=50)
class Activity(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE) # if a project is deleted, also delete its activities
    activity_name = models.CharField(max_length=100)
    duration = models.IntegerField(default=0)
    date_created = models.DateTimeField(default=timezone.now) # actual timezone function is passed

    def __str__(self):
        return self.activity_name

dyasynora_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Project, Event
from ckeditor.widgets import CKEditorWidget

class ProjectForm(forms.ModelForm):
    story = forms.CharField(widget=CKEditorWidget(config_name='special'), label=' ')

    class Meta:
        model = Project
        fields = ['title','image','story']

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['message','project','start_datetime','end_datetime']

dyasynora_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.db.models import Q

from .models import Project, Campaign, Event, Opportunity
from .models import Activity
from django.apps import apps
Profile = apps.get_model('users', 'Profile')
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from dyasynora_app.forms import ProjectForm, EventForm

from search_views.search import SearchListView
from search_views.filters import BaseFilter

def home(request):
    context = {
        'projects': Project.objects.all() # Query data from DB
    }
    query = ""
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)
    return render(request, 'dyasynora_app/diasynora.html', context)

class SearchResultsView(ListView):
    model = Project
    template_name = 'dyasynora_app/search_results.html'

    def get_queryset(self): 
        query = self.request.GET.get('q')
        object_list = Project.objects.filter(
            Q(title__icontains=query) | Q(story__icontains=query)
        )
        return object_list

def crowdsourcers(request):
    return render(request, 'dyasynora_app/crowdsourcers.html')

# returns query set object containing a dictionary
def activities_json(request):
    return JsonResponse({
        'activities' : list(Activity.objects.values())
    })

def user_projects(request):
    projects = Project.objects.all()
    context = {
        'projects': projects.order_by('-date_created'),
    }
    return render(request, 'dyasynora_app/user_projects.html', context)

def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            project = form.save(commit=False)
            project.save()
            return redirect('/')
    else:
        form = ProjectForm()
    return render(request, 'dyasynora_app/project_form.html', {'form': form})

def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            event = form.save(commit=False)
            event.save()
            return redirect('/')
    else:
        form = EventForm()
    return render(request, 'dyasynora_app/event_form.html', {'form': form})

@csrf_exempt
def new_activity(request):
    activity_name = request.POST['activity_name']
    duration = request.POST['duration']
    activity = Activity(activity_name = activity_name, duration = duration)
    project.save()
    return JsonResponse({
        'id' : activity.id,
        'activity_name' : activity.activity_name,
        'duration' : activity.duration
    })

class PostListView(ListView):
    model = Project
    template_name = 'dyasynora_app/feed.html'
    context_object_name = 'projects'
    ordering = ['-date_created']

class ProjectDetailView(DetailView):
    model = Project
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context['campaigns'] = Campaign.objects.all()
        context['events'] = Event.objects.all()
        context['opportunities'] = Opportunity.objects.all()
        return context

class UserDetailView(DetailView):
    model = Profile

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['title', 'description', 'image', 'location']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['title', 'image', 'story']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.author:
            return True
        return False

class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    success_url = '/'

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.author:
            return True
        return False

def get_project_queryset(query=None):
    queryset = []
    queries = query.split(" ") #python install 2019 = [python, install, 2019]
    for q in queries:
        project = Project.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()

        for project in projects:
            queryset.append(project)

    return list(set(queryset))

def payment(request):
    return render(request, 'dyasynora_app/payment.html', {'title': 'DiaSynora'})

def our_mission(request):
    return render(request, 'dyasynora_app/our-mission.html', {'title': 'DiaSynora'})

def user_profile(request):
    return render(request, 'dyasynora_app/user-profile.html')

def leaders(request):
    return render(request, 'dyasynora_app/leaders.html', {'title': 'DiaSynora'})

def login(request):
    return render(request, 'dyasynora_app/login.html')

def register(request):
    return render(request, 'dyasynora_app/register.html')

def projects(request):
    latest_project_list = Project.objects.order_by('-date_created')[:5]
    context = {'latest_project_list': latest_project_list}
    return render(request, 'dyasynora_app/projects.html', context)

dyasynora_app/templates/dyasynora_app/project_detail.html
{% extends "dyasynora_app/base.html" %}
  {% block content %}
  <div style="padding:1em;">
  <div class="container">
    <!-- Campaign Modal -->
    <div class="modal fade" id="campaignmodal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="campaign-modal-label"></h5>
            <button type="button" class="close close-campaign-modal" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" id="campaign-modal-body">
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-campaign-modal" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- End Campaign Modal -->

    <!-- Event Modal -->
    <div class="modal fade" id="eventmodal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="event-modal-label"></h5>
            <button type="button" class="close close-event-modal" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" id="event-modal-body">
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-event-modal" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- End Event Modal -->

  {% if object.author == user %}
  <div class="c">
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'update-project' object.id %}">Edit Project</a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'delete-project' object.id %}">Delete</a>
  </div>
  {% endif %}
  <div class="proj-center">
  <div class="col-lg c">
    <div class="proj-title"><h1>{{object.title}}</h1></div>
    <p title="Project Location"><i class="fas fa-map-marker-alt"></i> Bahri, Khartoum &nbsp;
       <i class="fas fa-hand-holding-usd"></i>
       <span class="sponsor-color">
           {% if object.campaign_set.all.count == 1 %}
           {{object.campaign_set.all.count}} campaign
           {% else %}
           {{object.campaign_set.all.count}} campaigns
           {% endif %}
         </span> &nbsp;
       <i class="far fa-calendar-alt"></i>
       <span class="volunteer-color">
         {% if object.event_set.all.count == 1 %}
         {{object.event_set.all.count}} event
         {% else %}
         {{object.event_set.all.count}} events
         {% endif %}
       </span> &nbsp;
       <i class="fas fa-chalkboard-teacher"></i>
       <span class="mentor-color">
         {% if object.opportunity_set.all.count == 1 %}
         {{object.opportunity_set.all.count}} opportunity
         {% else %}
         {{object.opportunity_set.all.count}} opportunities
         {% endif %}
       </span>
    </p>
  </div>
  <div class="row proj-center">
    <div class="col-lg">
    <img class="proj-img-center" src="{{object.image.url}}">
    </div>
    <div class="col-lg">
      {% if object.campaign_set.all.count != 0%}
      <h2 style="color:#E9C46A;">
        809,760 SDG
        <span style="color:grey;font-size:0.3em;" class="small">
          raised on
          {% if object.campaign_set.all.count != 0 %}
            {% if object.campaign_set.all.count == 1 %}
            {{object.campaign_set.all.count}} campaign
            {% else %}
            {{object.campaign_set.all.count}} campaigns
            {% endif %}
          {% endif %}
        </span>
      </h2>
      <div class="progress">
        <div class="progress-bar bg-success" role="progressbar" style="width: 86%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      {% endif %}
      {% if object.event_set.all.count != 0%}
      <h2 style="color:#F4A261;">
      239
      <span style="color:grey;font-size:0.3em;" class="small">
        volunteers on
        {% if object.event_set.all.count != 0 %}
          {% if object.event_set.all.count == 1 %}
          {{object.event_set.all.count}} event
          {% else %}
          {{object.event_set.all.count}} events
          {% endif %}
        {% endif %}
      </span>
    </h2>
      {% endif %}
      {% if object.opportunity_set.all.count != 0%}
      <h2 style="color:#E76F51;">
       23
      <span style="color:grey;font-size:0.3em;" class="small">
        mentors on
        {% if object.opportunity_set.all.count != 0 %}
          {% if object.opportunity_set.all.count == 1 %}
          {{object.opportunity_set.all.count}} opportunity
          {% else %}
          {{object.opportunity_set.all.count}} opportunities
          {% endif %}
        {% endif %}
      </span>
      </h2>
      {% endif %}
      <div onclick="location.href='{% url 'dyasynora_app-profile-detail' object.author.id %}';" style="cursor: pointer;" class="row author-div">
      <div class="col-3">
        <img class="proj-author-img" src="{{object.author.profile.image.url}}">
      </div>
      <div class="col-9">
      <span style="font-size:0.7em;"> Project by:</span><br>
      <span><b>{{object.author.profile.first_name}} {{object.author.profile.last_name}}</b></span><br>
      <span style="font-size:0.7em;">{{object.author.project_set.count}} projects | 3 supported </span>
      </div>
     </div>
    </div>
  </div>
  <ul class="nav nav-pills tabs-center nav-justified" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a onclick="changeBg('#2A9D8F','pills-story-tab');" style="border-radius: 10px; border: solid 3px #2A9D8F;" class="nav-link p-2" id="pills-story-tab" data-toggle="pill" href="#pills-story" role="tab" aria-controls="pills-story" title="Project Story" aria-selected="true">Story</a>
  </li>
  <li class="nav-item">
    <a onclick="changeBg('#E9C46A','pills-campaigns-tab');" style="border-radius: 10px; border: solid 3px #E9C46A;" class="nav-link p-2" id="pills-campaigns-tab" data-toggle="pill" href="#pills-campaigns" role="tab" aria-controls="pills-campaigns" title="Project Campaigns" aria-selected="false">Campaigns</a>
  </li>
  <li class="nav-item">
    <a onclick="changeBg('#F4A261','pills-events-tab');" style="border-radius: 10px; border: solid 3px #F4A261;" class="nav-link p-2" id="pills-events-tab" data-toggle="pill" href="#pills-events" role="tab" aria-controls="pills-events" title="Project Events" aria-selected="false">Events</a>
  </li>
  <li class="nav-item">
    <a onclick="changeBg('#E76F51','pills-opportunities-tab');" style="border-radius: 10px; border: solid 3px #E76F51;" class="nav-link p-2" id="pills-opportunities-tab" data-toggle="pill" href="#pills-opportunities" role="tab" aria-controls="pills-opportunities" title="Project Opportunities" aria-selected="false">Opportunities</a>
  </li>
  <li class="nav-item">
    <a onclick="changeBg('#264653','pills-overview-tab');" style="border-radius: 10px; border: solid 3px #264653;" class="nav-link p-2" id="pills-overview-tab" data-toggle="pill" href="#pills-overview" role="tab" aria-controls="pills-overview" title="Project Overview" aria-selected="false">Overview</a>
  </li>
  </ul>
<div class="tab-content tabs-center" id="pills-tabContent">
  <div style="border-radius: 10px; padding:30px;border: 3px solid #2A9D8F;" class="tab-pane fade show active" id="pills-story" role="tabpanel" aria-labelledby="pills-story-tab">
    {{object.story|safe}}
  </div>
  <div style="border-radius: 10px; padding:30px; border: 3px solid #E9C46A;" class="tab-pane fade" id="pills-campaigns" role="tabpanel" aria-labelledby="pills-campaigns-tab">
      <div class="row">
      {% for campaign in campaigns %}
      {% if campaign.project == object %}
        <div data-toggle="modal" data-id="{{campaign.title}}" id="{{campaign.description}}" data-target="#campaignmodal" style="cursor: pointer;" class="open-campaign-modal shadow-sm col-xl-3 col-lg-4 col-md-6 mb-4">
          <div class="preview-crop zoom bg-white rounded">
            <img src="{{campaign.image.url}}" class="cropped img-fluid card-img-top">
            <div class="p-4">
            <h6><b>{{campaign.title}}</b></h6>
            <p class="small">{{campaign.description}}</p>
            <div class="d-flex align-items-center justify-content-between rounded-pill px-3 py-2 mt-4">
              {{campaign.amount}}
            </div>
          </div>
        </div>
          <br>
        </div>
      {% endif %}
    {% endfor %}
    </div>
  </div>
  <div style="border-radius: 10px; padding:30px; border: 3px solid #F4A261;" class="tab-pane fade" id="pills-events" role="tabpanel" aria-labelledby="pills-contact-events">
    <div class="row">
      {% for event in events %}
      {% if event.project == object %}
        <div data-toggle="modal" data-id="{{event.name}}" id="{{event.message}}" data-target="#eventmodal" style="cursor: pointer;" class="open-event-modal shadow-sm col-xl-3 col-lg-4 col-md-6 mb-4">
          <div class="preview-crop zoom bg-white rounded">
            <img src="{{event.image.url}}" class="cropped img-fluid card-img-top">
            <div class="p-4">
            <h6><b>{{event.name}}</b></h6>
            <p class="small">{{event.message}}</p>
            <div class="d-flex align-items-center justify-content-between rounded-pill px-3 py-2 mt-4">
              {{campaign.amount}}
            </div>
          </div>
        </div>
        <div>
          <br>
          </div>
        </div>
      {% endif %}
    {% endfor %}
    </div>
  </div>
  <div style="border-radius: 10px; padding:30px; border: 3px solid #E76F51;" class="tab-pane fade" id="pills-opportunities" role="tabpanel" aria-labelledby="pills-opportunities-tab">
    <div class="row">
      {% for opportunity in opportunities %}
      {% if opportunity.project == object %}
       <div onclick="location.href='{% url 'dyasynora_app-project-detail' project.id %}';" style="cursor: pointer;" class="shadow-sm col-xl-3 col-lg-4 col-md-6 mb-4">
        <div class="preview-crop zoom bg-white rounded">
          <img src="{{opportunity.image.url}}" class="cropped img-fluid card-img-top">
          <div class="p-4">
          <h6><b>{{opportunity.title}}</b></h6>
          <p class="small">{{opportunity.description}}</p>
          <div class="d-flex align-items-center justify-content-between rounded-pill px-3 py-2 mt-4">
            {{opportunity.amount}}
          </div>
        </div>
      </div>
      <div>
        <br>
      </div>
      </div>
      {% endif %}
    {% endfor %}
    </div>
  </div>
  <div style="border-radius: 10px; padding:30px; border: 3px solid #264653;" class="tab-pane fade" id="pills-overview" role="tabpanel" aria-labelledby="pills-overview-tab">
    The {{object.title}} journey so far
  </div>
</div>
</div>
</div>
</div>
  {% endblock content %}

dyasynora_app/templates/dyasynora_app/search_results.html
{% extends "dyasynora_app/base.html" %}
  {% block content %}
  <div style="padding:2em;">
  <small class="text-muted">Search results</small>
  <br><br>
  <div style="padding:1em;" class="container-fluid">
    <div class="px-lg-5">
      <div class="row">
{% for project in object_list %}
<div onclick="location.href='{% url 'dyasynora_app-project-detail' project.id %}';" style="cursor: pointer;" class="col-xl-3 col-lg-4 col-md-6 mb-4 filter
{% if project.campaign_set.all.count != 0 %}
  campaign
{% endif %}
{% if project.event_set.all.count != 0 %}
  event
{% endif %}
{% if project.opportunity_set.all.count != 0 %}
  opportunity
{% endif %}">
  <div class="feed zoom bg-white rounded shadow-sm">
      <img src="{{project.image.url}}" class="cropped img-fluid card-img-top">
    <div class="p-4">
      <div class="row author-div">
      <div class="col-3">
        <img class="proj-author-img-feed" src="{{project.author.profile.image.url}}">
      </div>
      <div class="col-9">
      <span style="font-size:0.7em;"><b>{{project.author.profile.first_name}} {{project.author.profile.last_name}}</b></span><br>
      <span style="font-size:0.6em;">London, UK{{project.author.profile.location}}</span>
    </div>
     </div>
      <h5><b>{{project.title}}</b></h5>
      <div class="story-crop"><p class="small">{{project.story|safe}}</p></div>
      <div class="badge-crop d-flex align-items-center justify-content-between rounded-pill px-3 py-2 mt-4">
        {% if project.campaign_set.all.count != 0 %}
          {% if project.campaign_set.all.count == 1 %}
          <div style="background-color:#E9C46A" class="badge px-3 rounded-pill font-weight-normal">{{project.campaign_set.all.count}}  Campaign</div>
          {% else %}
          <div style="background-color:#E9C46A" class="badge px-3 rounded-pill font-weight-normal">{{project.campaign_set.all.count}} Campaigns</div>
          {% endif %}
        {% endif %}
        {% if project.event_set.all.count != 0 %}
          {% if project.event_set.all.count == 1 %}
          <div style="background-color:#F4A261" class="badge px-3 rounded-pill font-weight-normal">{{project.event_set.all.count}}  Event</div>
          {% else %}
            <div style="background-color:#F4A261" class="badge px-3 rounded-pill font-weight-normal">{{project.event_set.all.count}}  Events</div>
          {% endif %}
        {% endif %}
        {% if project.opportunity_set.all.count != 0 %}
          {% if project.opportunity_set.all.count == 1 %}
          <div style="background-color:#E76F51" class="badge px-3 rounded-pill font-weight-normal">{{project.opportunity_set.all.count}}  Opportunity</div>
          {% else %}
            <div style="background-color:#E76F51" class="badge px-3 rounded-pill font-weight-normal">{{project.opportunity_set.all.count}} Opportunities</div>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% empty %}
        <p> Sorry, there were no results found :( </p>
{% endfor %}
</div></div></div>
</div>
  {% endblock content %}